# AndroidX properties
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# SDK compatibility settings
android.builder.sdkInstallPath=/Users/shileipeng/Library/Android/sdk
android.suppressUnsupportedCompileSdk=36
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
