name: iOSSDKExample
targets:
  iOSSDKExample:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources, "../../llama_mobile_vd-ios-SDK/LlamaMobileVDBundle/Sources/LlamaMobileVD"]
    settings:
      base:
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: "com.llamamobile.iOSSdkExample"
        FRAMEWORK_SEARCH_PATHS: ["../../llama_mobile_vd-ios-SDK/LlamaMobileVDBundle"]
    entitlements:
      path: iOSSDKExample.entitlements
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIViewControllerBasedStatusBarAppearance: true
    dependencies:
      - framework: "../../llama_mobile_vd-ios-SDK/LlamaMobileVDBundle/llama_mobile_vd.xcframework"
        embed: true
        codeSign: true
