pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "androidSDKExample"
include ':app'
include ':llama_mobile_vd-android-SDK'
project(':llama_mobile_vd-android-SDK').projectDir = new File(rootProject.projectDir, '../../llama_mobile_vd-android-SDK')
