name: llama_mobile_vd_flutter_sdk
description: Flutter SDK for Llama Mobile Vector Database
version: 0.0.1
homepage: https://github.com/llama-mobile/llama_mobile_vd

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LlamaMobileVDFlutterPlugin
      android:
        package: com.llamamobile.vd
        pluginClass: LlamaMobileVDFlutterPlugin

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
